account.msg = Welcome to the Meng Bank account Prodution 2026
account.build-version=3

account.mailDetails.hostName=prod-account@meng.com
account.mailDetails.port=9000
account.mailDetails.from=prod-account@meng.com
account.mailDetails.subject=Your Account Details from Meng Bank prod  Environment

account.activeBranches[0]=Kandal
account.activeBranches[1]=Kompong Chhnang
account.activeBranches[2]=Svay Reang
