account.msg = Welcome to the Meng Bank account Dev application
account.build-version=3

account.mailDetails.hostName=dev-account@meng.com
account.mailDetails.port=9000
account.mailDetails.from=dev-account@meng.com
account.mailDetails.subject=Your Account Details from Meng Bank Dev  Environment

account.activeBranches[0]=Kompong Thom
account.activeBranches[1]=Kompong Cham
account.activeBranches[2]=Preah Vihea