card.msg = Welcome to the Meng Bank card Dev application
card.build-version=3

card.mailDetails.hostName=dev-card@meng.com
card.mailDetails.port=9000
card.mailDetails.from=dev-card@meng.com
card.mailDetails.subject=Your card Details from Meng Bank Dev  Environment

card.activeBranches[0]=Kompong Thom
card.activeBranches[1]=Kompong Cham
card.activeBranches[2]=Preah Vihea