card.msg = Welcome to the Meng Bank card Prodution application
card.build-version=3

card.mailDetails.hostName=prod-card@meng.com
card.mailDetails.port=9000
card.mailDetails.from=prod-card@meng.com
card.mailDetails.subject=Your card Details from Meng Bank prod  Environment

card.activeBranches[0]=Kandal
card.activeBranches[1]=Kompong Chhnang
card.activeBranches[2]=Svay Reang